name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the iandennismiller/jekyll container
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          iandennismiller/jekyll:latest \
          /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future" && \
        cd ${{ github.workspace }}/_site && \
        remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" && \
        remote_branch="gh-pages" && \
        git init -b gh-pages && \
        git config user.name "${GITHUB_ACTOR}" && \
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
        git add . && \
        echo -n 'Files to Commit:' && ls -l | wc -l && \
        git commit -m'action build' > /dev/null 2>&1 && \
        git push --force $remote_repo main:$remote_branch > /dev/null 2>&1 && \
        rm -fr .git && \
        cd ../
        echo '👍 GREAT SUCCESS!'

